file(GLOB paths RELATIVE "${CMAKE_CURRENT_BINARY_DIR}" "${CMAKE_CURRENT_BINARY_DIR}/*")
file(ARCHIVE_CREATE OUTPUT "${OUTPUT}" PATHS ${paths}
    FORMAT gnutar COMPRESSION GZip MTIME "1970-01-01 00:00:00 UTC")
